### ISSUE TITLE
Need to require python>=3.10 instead of python>=3.9

### ISSUE THREAD

**Issue by kevinli1993** [sphinx-doc/sphinx-autobuild#166]
Due to the usage of the `strict` argument in server.py
```python
self.paths = [os.path.realpath(path, strict=True) for path in paths]
```
we need to require Python 3.10 or above.   (Per [the documentation](https://docs.python.org/3/library/os.path.html#os.path.realpath), the `strict` argument is only available after Python 3.10).

Running with Python 3.9 results in the following error/traceback:
```
$ sphinx-autobuild ... .../_build/html
Traceback (most recent call last):
  File "..../bin/sphinx-autobuild", line 8, in <module>
    sys.exit(main())
  File "..../lib/python3.9/site-packages/sphinx_autobuild/__main__.py", line 54, in main
    watcher = RebuildServer(watch_dirs, ignore_handler, change_callback=builder)
  File "..../lib/python3.9/site-packages/sphinx_autobuild/server.py", line 27, in __init__
    self.paths = [os.path.realpath(path, strict=True) for path in paths]
  File "..../lib/python3.9/site-packages/sphinx_autobuild/server.py", line 27, in <listcomp>
    self.paths = [os.path.realpath(path, strict=True) for path in paths]
TypeError: realpath() got an unexpected keyword argument 'strict'
```

**Comment by KyeRussell** [comment]
Python 3.9 support has been fixed in (unreleased) https://github.com/sphinx-doc/sphinx-autobuild/pull/157

**Comment by AA-Turner** [comment]
https://pypi.org/project/sphinx-autobuild/2024.9.3/

A
