### ISSUE TITLE
Got an error while trying to run the dev server

### ISSUE THREAD

**Issue by Skrillx13** [sphinx-doc/sphinx-autobuild#172]
I have this brand new Sphinx Project, and i installed the auto dev server onto it with pip. When i ran sphinx-autobuild docs docs/build/html (I set it to this path cus my folder is called build, not _build), i got this error:

(venv) jonathanfong@EdFongMBPro-2 DocStrings % sphinx-autobuild docs docs/build/html 
Traceback (most recent call last):
  File "/Users/jonathanfong/DocStrings/venv/bin/sphinx-autobuild", line 8, in <module>
    sys.exit(main())
  File "/Users/jonathanfong/DocStrings/venv/lib/python3.9/site-packages/sphinx_autobuild/__main__.py", line 54, in main
    watcher = RebuildServer(watch_dirs, ignore_handler, change_callback=builder)
  File "/Users/jonathanfong/DocStrings/venv/lib/python3.9/site-packages/sphinx_autobuild/server.py", line 27, in __init__
    self.paths = [os.path.realpath(path, strict=True) for path in paths]
  File "/Users/jonathanfong/DocStrings/venv/lib/python3.9/site-packages/sphinx_autobuild/server.py", line 27, in <listcomp>
    self.paths = [os.path.realpath(path, strict=True) for path in paths]
TypeError: realpath() got an unexpected keyword argument 'strict'

Inside my project theres a venv folder, but thats because i use a python virtual enviroment. Is this supposed to happen?

**Comment by AA-Turner** [comment]
https://pypi.org/project/sphinx-autobuild/2024.9.3/

A
